"""empty message

Revision ID: 311fe11425c9
Revises: 2ae983a25414
Create Date: 2021-03-15 15:50:18.918183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311fe11425c9'
down_revision = '2ae983a25414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255)))
    op.execute('UPDATE users SET password=email')
    op.alter_column('users', 'password', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
